### ISSUE TITLE
Incorrectly assumes CCD means credit

### ISSUE THREAD

**Issue by jdforsythe** [philipwhitt/nacha-generator#10]
This library incorrectly assumes that only CCD entries can be credits, and that all credits must be CCD entries.

Per the NACHA spec, CCD entries can be credit or debit entries, and other types of entries can be credit entries (e.g. PPD).

**Comment by philipwhitt** [comment]
Where specifically?

**Comment by jdforsythe** [comment]
`Batch->addCreditEntry(CcdEntry $entry)` in Batch.php

**Comment by jdforsythe** [comment]
In reality the only difference between CCD and PPD or WEB is that it's a company name rather than an individual name (although we use PPD for non-profit orgs) - so in the PR #9 I just changed Entry to use "subject" rather than individual or company, and it eliminates the need for a separate classes altogether

**Comment by philipwhitt** [comment]
There is now a addEntry() method. addDebitEntry() and addCreditEntry() are effectively deprecated now, but still around to maintain the api.
